<a href="https://colab.research.google.com/github/Jaidon-Smith/AI-Karaoke/blob/main/Japanese%20Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Japanese Speech to Text

In [5]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [3]:
colab_environment = True
document_url = "https://colab.research.google.com/github/Jaidon-Smith/public-datasets/blob/main/Jsut%20dataset.ipynb#scrollTo=3GrHu19HO5Em"

if colab_environment:
  #Get the github ssh command and cd directory from the document url
  import urllib 
  document_url = urllib.parse.unquote(document_url)
  repository_ssh = "/".join(document_url.split("github/")[1].split("/")[0:2])
  repository_ssh = "git@github.com:{}.git".format(repository_ssh)
  directory_name = "/".join(document_url.split("github/")[1].split("/")[4:-1])
  # Mount google drive
  from google.colab import drive
  drive.mount('/content/drive')
  # Copy the ssh folder from my google drive to the root
  !cp -R "/content/drive/My Drive/Colab Notebooks/github_integration/.ssh" "/root/"
  # Copy the gitconfig folder from my google drive to the root
  !cp "/content/drive/My Drive/Colab Notebooks/github_integration/.gitconfig" "/root/"
  # Clone repository into virtual macine hardrive
  !git clone $repository_ssh
  # cd into the directory
  repository_name = repository_ssh.split("/")[1].split(".")[0]
  directory = "/content/{}/{}".format(repository_name, directory_name)
  %cd $directory

Mounted at /content/drive
Cloning into 'public-datasets'...
remote: Enumerating objects: 228, done.
remote: Counting objects: 100% (228/228), done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 228 (delta 115), reused 132 (delta 56), pack-reused 0
Receiving objects: 100% (228/228), 35.89 KiB | 216.00 KiB/s, done.
Resolving deltas: 100% (115/115), done.
/content/public-datasets


In [ ]:
!pip install --quiet tensorflow-text

import tensorflow_text as text
from tensorflow.python.platform import gfile

     |████████████████████████████████| 3.4MB 5.7MB/s 


In [ ]:
model_file = '/gdrive/MyDrive/Japanese/Bible/letters.model'
model = gfile.GFile(model_file, 'rb').read()

tokenizer = text.SentencepieceTokenizer(model=model)

FailedPreconditionError: ignored

In [ ]:
tokenizer.tokenize('英語が分かりますか')

NameError: ignored

## JSUT dataset

In [ ]:
!wget https://drive.google.com/file/d/1vpuAmGlNfScse31aD2BEyasxjbLOADbl/view?usp=sharing

--2021-02-24 03:24:00--  https://drive.google.com/file/d/1vpuAmGlNfScse31aD2BEyasxjbLOADbl/view?usp=sharing
Resolving drive.google.com (drive.google.com)... 142.250.103.102, 142.250.103.100, 142.250.103.139, ...
Connecting to drive.google.com (drive.google.com)|142.250.103.102|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/ServiceLogin?service=wise&passive=1209600&continue=https://drive.google.com/file/d/1vpuAmGlNfScse31aD2BEyasxjbLOADbl/view?usp%3Dsharing&followup=https://drive.google.com/file/d/1vpuAmGlNfScse31aD2BEyasxjbLOADbl/view?usp%3Dsharing [following]
--2021-02-24 03:24:00--  https://accounts.google.com/ServiceLogin?service=wise&passive=1209600&continue=https://drive.google.com/file/d/1vpuAmGlNfScse31aD2BEyasxjbLOADbl/view?usp%3Dsharing&followup=https://drive.google.com/file/d/1vpuAmGlNfScse31aD2BEyasxjbLOADbl/view?usp%3Dsharing
Resolving accounts.google.com (accounts.google.com)... 74.125.129.84, 2607:f8b

In [ ]:
jsut_zip = '/gdrive/MyDrive/datasets/jsut_ver1.1.zip'

In [ ]:
!pip install tfds-nightly

     |████████████████████████████████| 3.8MB 5.8MB/s 


In [ ]:
import tensorflow_datasets as tfds

In [ ]:
!tfds new jsut_beta

2021-02-24 02:20:55.926219: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Dataset generated at /content/AI-Karaoke/jsut_beta
You can start searching `TODO(jsut_beta)` to complete the implementation.
Please check https://www.tensorflow.org/datasets/add_dataset for additional details.


In [ ]:
builder = tfds.builder('jsut_beta')
# 1. Create the tfrecord files (no-op if already exists)
download_config = tfds.download.DownloadConfig(manual_dir='/content/drive/MyDrive/datasets/jsut')
#builder.download_and_prepare(download_config=download_config)
builder.download_and_prepare(download_config=download_config)

# 2. Load the `tf.data.Dataset`
ds = builder.as_dataset(split='train', shuffle_files=True)
print(ds)

<_OptionsDataset shapes: {id: (), speech: (None,), text: ()}, types: {id: tf.string, speech: tf.int64, text: tf.string}>


In [ ]:
import jsut_beta.jsut_beta
import importlib
importlib.reload(jsut_beta.jsut_beta)


<module 'jsut_beta.jsut_beta' from '/content/AI-Karaoke/jsut_beta/jsut_beta.py'>

In [ ]:
!pip install pydub

In [ ]:
data_take = ds.take(1)

In [ ]:
for data in data_take:
  data_point = data
  break

In [ ]:
text = data_point

{'id': <tf.Tensor: shape=(), dtype=string, numpy=b'BASIC5000_4696'>,
 'speech': <tf.Tensor: shape=(98400,), dtype=int64, numpy=array([-152, -163, -179, ...,  -28,  -28,  -28])>,
 'text': <tf.Tensor: shape=(), dtype=string, numpy=b'\xe5\x8e\xb3\xe3\x81\x97\xe3\x81\x84\xe5\x8f\xb1\xe8\xb2\xac\xe3\x82\x92\xe5\x8f\x97\xe3\x81\x91\xe3\x82\x8b\xe3\x80\x82'>}

In [ ]:
!mkdir /content/drive/MyDrive/datasets/jsut/jsut_beta

In [ ]:
!cp -R /root/tensorflow_datasets/jsut_beta /content/drive/MyDrive/datasets/jsut/jsut_beta

In [ ]:
!git clone https://github.com/Jaidon-Smith/public-datasets.git

fatal: destination path 'public-datasets' already exists and is not an empty directory.


In [ ]:
%cd ..

/content


In [ ]:
!rm -R public-datasets

In [ ]:
import jsut
import importlib
importlib.reload(jsut)

<module 'jsut' from '/content/public-datasets/jsut/__init__.py'>

In [ ]:
%cd public-datasets/

[Errno 2] No such file or directory: 'public-datasets/'
/content/public-datasets


In [ ]:
import 

In [ ]:
download_config = tfds.download.DownloadConfig(manual_dir='/gdrive/MyDrive/datasets/public_datasets/downloads/manual')

ds = tfds.load("jsut", data_dir='/gdrive/MyDrive/datasets/public_datasets', download_and_prepare_kwargs={"download_config": download_config})

The manual directory is:  /gdrive/MyDrive/datasets/public_datasets/downloads/manual


KeyboardInterrupt: ignored

In [ ]:
download_config = tfds.download.DownloadConfig(manual_dir='/gdrive/MyDrive/datasets/public_datasets/downloads/manual')

ds = tfds.load("jsut", download_and_prepare_kwargs={"download_config": download_config})

The manual directory is:  /gdrive/MyDrive/datasets/public_datasets/downloads/manual


KeyboardInterrupt: ignored

In [ ]:
download_config = tfds.download.DownloadConfig(manual_dir='/gdrive/MyDrive/datasets/tensorflow_datasets/')

#builder = tfds.builder('jsut', data_dir='/gdrive/MyDrive/datasets/')
builder = tfds.builder('jsut')
builder.download_and_prepare(download_config=download_config)
ds = builder.as_dataset(split='train', shuffle_files=True)
print(ds)

The manual directory is:  /gdrive/MyDrive/datasets/tensorflow_datasets/


ExtractError: ignored

In [ ]:
%cd public-datasets/

/content/public-datasets


In [ ]:
%cd /content

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-84160950ea11>", line 1, in <module>
    get_ipython().magic('cd /content')
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2160, in magic
    return self.run_line_magic(magic_name, magic_arg_s)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2081, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-84>", line 2, in cd
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/magic.py", line 188, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/magics/osm.py", line 288, in cd
    oldcwd = py3compat.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another

FileNotFoundError: ignored

## Common Voice Dataset

In [ ]:
%cd public-datasets/

/content/public-datasets


In [ ]:
import tensorflow_datasets as tfds

In [ ]:
import common_voice_v6

<module 'common_voice_v6' from '/content/public-datasets/common_voice_v6/__init__.py'>

In [ ]:
#download_config = tfds.download.DownloadConfig(manual_dir='/gdrive/MyDrive/datasets/public_datasets/downloads/manual')
download_config = tfds.download.DownloadConfig(manual_dir='/gdrive/MyDrive/datasets/public_datasets/downloads/manual/commonvoice')

#ds = tfds.load("common_voice_v6/ja", split='train', download_and_prepare_kwargs={"download_config": download_config})
#ds = tfds.load("jsut", download_and_prepare_kwargs={"download_config": download_config})

#download_config = tfds.download.DownloadConfig(manual_dir='/gdrive/MyDrive/datasets/public_datasets/downloads/manual')

ds = tfds.load("common_voice_v6/ja", data_dir='/gdrive/MyDrive/datasets/public_datasets', download_and_prepare_kwargs={"download_config": download_config})

The manual directory is:  /gdrive/MyDrive/datasets/public_datasets/downloads/manual/commonvoice


Audio:  /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/TAR.ja.tar/cv-corpus-6.1-2020-12-11/ja/clips
Label:  /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/TAR.ja.tar/cv-corpus-6.1-2020-12-11/ja/train.tsv


Audio:  /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/TAR.ja.tar/cv-corpus-6.1-2020-12-11/ja/clips
Label:  /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/TAR.ja.tar/cv-corpus-6.1-2020-12-11/ja/test.tsv


Audio:  /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/TAR.ja.tar/cv-corpus-6.1-2020-12-11/ja/clips
Label:  /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/TAR.ja.tar/cv-corpus-6.1-2020-12-11/ja/validated.tsv


Dataset common_voice_v6 downloaded and prepared to /gdrive/MyDrive/datasets/public_datasets/common_voice_v6/ja/1.0.0. Subsequent calls will reuse this data.


# Tatoeba Japanese

In [7]:
!pip install tfds-nightly
!pip install pydub

     |████████████████████████████████| 3.8MB 10.8MB/s 


In [1]:
%cd public-datasets/

/content/public-datasets


In [2]:
import tensorflow_datasets as tfds

In [3]:
import tatoeba_japanese

In [5]:
download_config = tfds.download.DownloadConfig(manual_dir='/gdrive/MyDrive/datasets/public_datasets/downloads/manual/')

ds = tfds.load("tatoeba_japanese", data_dir='/gdrive/MyDrive/datasets/public_datasets', download_and_prepare_kwargs={"download_config": download_config})

# JVS Corpus

In [2]:
!pip install tfds-nightly
!pip install pydub

     |████████████████████████████████| 3.8MB 4.7MB/s 


In [1]:
%cd public-datasets/

/content/public-datasets


In [2]:
import tensorflow_datasets as tfds

In [3]:
import jvs

In [4]:
download_config = tfds.download.DownloadConfig(manual_dir='/gdrive/MyDrive/datasets/public_datasets/downloads/manual/')

ds = tfds.load("jvs", data_dir='/gdrive/MyDrive/datasets/public_datasets', download_and_prepare_kwargs={"download_config": download_config})

The manual directory is:  /gdrive/MyDrive/datasets/public_datasets/downloads/manual


Folder: /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/ZIP.jvs_ver1.zip/jvs_ver1/jvs075/parallel100
Folder: /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/ZIP.jvs_ver1.zip/jvs_ver1/jvs075/whisper10
Folder: /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/ZIP.jvs_ver1.zip/jvs_ver1/jvs075/nonpara30
Folder: /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/ZIP.jvs_ver1.zip/jvs_ver1/jvs075/falset10
Folder: /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/ZIP.jvs_ver1.zip/jvs_ver1/jvs063/parallel100
Folder: /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/ZIP.jvs_ver1.zip/jvs_ver1/jvs063/whisper10
Folder: /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/ZIP.jvs_ver1.zip/jvs_ver1/jvs063/nonpara30
Folder: /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/ZIP.jvs_ver1.zip/jvs_ver1/jvs063/falset10
Folder: /gdrive/MyDrive/datasets/public_datasets/downloads/extracted/ZIP.jvs_ver1.zip/jvs_ver1/jvs047/

Dataset jvs downloaded and prepared to /gdrive/MyDrive/datasets/public_datasets/jvs/1.1.0. Subsequent calls will reuse this data.
