<a href="https://colab.research.google.com/github/Jaidon-Smith/AI-Karaoke/blob/main/SileroTokenization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SentencePiece

In [1]:
!pip install sentencepiece

     |████████████████████████████████| 1.2MB 9.1MB/s 


In [2]:
!wget https://raw.githubusercontent.com/google/sentencepiece/master/data/botchan.txt
!wget https://storage.googleapis.com/ai-karaoke-311510-america/silero_tokens.model
!wget https://storage.googleapis.com/ai-karaoke-311510-america/vocals.wav

--2021-04-25 09:52:04--  https://raw.githubusercontent.com/google/sentencepiece/master/data/botchan.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 278779 (272K) [text/plain]
Saving to: ‘botchan.txt’

botchan.txt         100%[===================>] 272.25K  --.-KB/s    in 0.02s   

2021-04-25 09:52:04 (12.9 MB/s) - ‘botchan.txt’ saved [278779/278779]

--2021-04-25 09:52:04--  https://storage.googleapis.com/ai-karaoke-311510-america/silero_tokens.model
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.20.128, 108.177.98.128, 74.125.197.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.20.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 258689 (253K) [application/octet-stream]
Saving

In [3]:
labels = ["_", "th", "the", "in", "an", "re", "er", "on", "at", "ou", "is", "en", "to", "and", "ed", "al", "as", "it", "ing", "or", "of", "es", "ar", "he", "le", "st", "se", "om", "ic", "be", "we", "ly", "that", "no", "wh", "ve", "ha", "you", "ch", "ion", "il", "ent", "ro", "me", "id", "ac", "gh", "for", "was", "lo", "ver", "ut", "li", "ld", "ay", "ad", "so", "ir", "im", "un", "wi", "ter", "are", "with", "ke", "ge", "do", "ur", "all", "ce", "ab", "mo", "go", "pe", "ne", "this", "ri", "ght", "de", "one", "us", "am", "out", "fe", "but", "po", "his", "te", "ho", "ther", "not", "con", "com", "ll", "they", "if", "ould", "su", "have", "ct", "ain", "our", "ation", "fr", "ill", "now", "sa", "had", "tr", "her", "per", "ant", "oun", "my", "ul", "ca", "by", "what", "red", "res", "od", "ome", "ess", "man", "ex", "she", "pl", "co", "wor", "pro", "up", "thing", "there", "ple", "ag", "can", "qu", "art", "ally", "ok", "from", "ust", "very", "sh", "ind", "est", "some", "ate", "wn", "ti", "fo", "ard", "ap", "him", "were", "ich", "here", "bo", "ity", "um", "ive", "ous", "way", "end", "ig", "pr", "which", "ma", "ist", "them", "like", "who", "ers", "when", "act", "use", "about", "ound", "gr", "et", "ide", "ight", "ast", "king", "would", "ci", "their", "other", "see", "ment", "ong", "wo", "ven", "know", "how", "said", "ine", "ure", "more", "der", "sel", "br", "ren", "ack", "ol", "ta", "low", "ough", "then", "peo", "ye", "ace", "people", "ink", "ort", "your", "will", "than", "pp", "any", "ish", "look", "la", "just", "tor", "ice", "itt", "af", "these", "sp", "has", "gre", "been", "ty", "ies", "ie", "get", "able", "day", "could", "bl", "two", "time", "beca", "into", "age", "ans", "mis", "new", "ree", "ble", "ite", "si", "urn", "ass", "cl", "ber", "str", "think", "dis", "mar", "ence", "pt", "self", "ated", "did", "el", "don", "ck", "ph", "ars", "ach", "fore", "its", "part", "ang", "cre", "well", "ions", "where", "ves", "ved", "em", "good", "because", "over", "ud", "ts", "off", "turn", "cr", "right", "ress", "most", "every", "pre", "fa", "fir", "ild", "pos", "down", "work", "ade", "say", "med", "also", "litt", "little", "ance", "come", "ving", "only", "ful", "ought", "want", "going", "spe", "ps", "ater", "first", "after", "ue", "ose", "mu", "iz", "ire", "int", "rest", "ser", "coun", "des", "light", "son", "let", "ical", "ick", "ra", "back", "mon", "ase", "ign", "ep", "world", "may", "read", "form", "much", "even", "should", "again", "make", "long", "sto", "cont", "put", "thr", "under", "cor", "bet", "jo", "car", "ile", "went", "yes", "ually", "row", "hand", "ak", "call", "ary", "ia", "many", "cho", "things", "try", "gl", "ens", "really", "happ", "great", "dif", "bu", "hi", "made", "room", "ange", "cent", "ious", "je", "three", "ward", "op", "gen", "those", "life", "tal", "pa", "through", "und", "cess", "before", "du", "side", "need", "less", "inter", "ting", "ry", "ise", "na", "men", "ave", "fl", "ction", "pres", "old", "something", "miss", "never", "got", "feren", "imp", "sy", "ations", "tain", "ning", "ked", "sm", "take", "ten", "ted", "ip", "col", "own", "stand", "add", "min", "wer", "ms", "ces", "gu", "land", "bod", "log", "cour", "ob", "vo", "ition", "hu", "came", "comp", "cur", "being", "comm", "years", "ily", "wom", "cer", "kind", "thought", "such", "tell", "child", "nor", "bro", "ial", "pu", "does", "head", "clo", "ear", "led", "llow", "ste", "ness", "too", "start", "mor", "used", "par", "play", "ents", "tri", "upon", "tim", "num", "ds", "ever", "cle", "ef", "wr", "vis", "ian", "sur", "same", "might", "fin", "differen", "sho", "why", "body", "mat", "beg", "vers", "ouse", "actually", "ft", "ath", "hel", "sha", "ating", "ual", "found", "ways", "must", "four", "gi", "val", "di", "tre", "still", "tory", "ates", "high", "set", "care", "ced", "last", "find", "au", "inte", "ev", "ger", "thank", "ss", "ict", "ton", "cal", "nat", "les", "bed", "away", "place", "house", "che", "ject", "sol", "another", "ited", "att", "face", "show", "ner", "ken", "far", "ys", "lect", "lie", "tem", "ened", "night", "while", "looking", "ah", "wal", "dr", "real", "cha", "exp", "war", "five", "pol", "fri", "wa", "cy", "fect", "xt", "left", "give", "soci", "cond", "char", "bor", "point", "number", "mister", "called", "six", "bre", "vi", "without", "person", "air", "different", "lot", "bit", "pass", "ular", "youn", "won", "main", "cri", "ings", "den", "water", "human", "around", "quest", "ters", "ities", "feel", "each", "friend", "sub", "though", "saw", "ks", "hund", "hundred", "times", "lar", "ff", "amer", "scho", "sci", "ors", "lt", "arch", "fact", "hal", "himself", "gener", "mean", "vol", "school", "ason", "fam", "ult", "mind", "itch", "ped", "home", "young", "took", "big", "love", "reg", "eng", "sure", "vent", "ls", "ot", "ince", "thous", "eight", "thousand", "better", "mom", "appe", "once", "ied", "mus", "stem", "sing", "ident", "als", "uh", "mem", "produ", "stud", "power", "atch", "bas", "father", "av", "nothing", "gir", "pect", "unt", "few", "kes", "eyes", "sk", "always", "ared", "toge", "stru", "together", "ics", "bus", "fort", "ween", "rep", "ically", "small", "ga", "mer", "ned", "ins", "between", "yet", "stre", "hard", "system", "course", "year", "cept", "publ", "sim", "sou", "ready", "follow", "present", "rel", "turned", "sw", "possi", "mother", "io", "bar", "ished", "dec", "ments", "pri", "next", "ross", "both", "ship", "ures", "americ", "eas", "asked", "iness", "serv", "ists", "ash", "uni", "build", "phone", "lau", "ctor", "belie", "change", "interest", "peri", "children", "thir", "lear", "plan", "import", "ational", "har", "ines", "dist", "selves", "city", "sen", "run", "law", "ghter", "proble", "woman", "done", "heart", "book", "aut", "ris", "lim", "looked", "vid", "fu", "bab", "ately", "ord", "ket", "oc", "doing", "area", "tech", "win", "name", "second", "certain", "pat", "lad", "quite", "told", "ific", "ative", "uring", "gg", "half", "reason", "moment", "ility", "ution", "shall", "aur", "enough", "idea", "open", "understand", "vie", "contin", "mal", "hor", "qui", "address", "heard", "help", "inst", "oney", "whole", "gover", "commun", "exam", "near", "didn", "logy", "oh", "tru", "lang", "restaur", "restaurant", "design", "ze", "talk", "leg", "line", "ank", "ond", "country", "ute", "howe", "hold", "live", "comple", "however", "ized", "ush", "seen", "bye", "fer", "ital", "women", "net", "state", "bur", "fac", "whe", "important", "dar", "nine", "sat", "fic", "known", "having", "against", "soon", "ety", "langu", "public", "sil", "best", "az", "knew", "black", "velo", "sort", "seven", "imag", "lead", "cap", "ask", "alth", "ature", "nam", "began", "white", "sent", "sound", "vir", "days", "anything", "yeah", "ub", "blo", "sun", "story", "dire", "money", "trans", "mil", "org", "grow", "cord", "pped", "cus", "spo", "sign", "beaut", "goodbye", "inde", "large", "question", "often", "hour", "que", "pur", "town", "ield", "coming", "door", "lig", "ling", "incl", "partic", "keep", "engl", "move", "later", "ants", "food", "lights", "bal", "words", "list", "aw", "allow", "aren", "pret", "tern", "today", "believe", "almost", "bir", "word", "possible", "ither", "case", "ried", "ural", "round", "twent", "develo", "plain", "ended", "iting", "chang", "sc", "boy", "gy", "since", "ones", "suc", "cas", "national", "plac", "teen", "pose", "started", "mas", "fi", "fif", "afr", "fully", "grou", "wards", "girl", "e", "t", "a", "o", "i", "n", "s", "h", "r", "l", "d", "u", "c", "m", "w", "f", "g", "y", "p", "b", "v", "k", "'", "x", "j", "q", "z", "-", "2", " "]
print(len(labels))

999


In [4]:
import sentencepiece as spm



```python
with open('short.txt', 'w') as f:
  f.write("short hello")

spm.SentencePieceTrainer.train(input='short.txt', model_prefix='silero_tokens', vocab_size=1000, user_defined_symbols=labels[:-1],
                               bos_id=-1, eos_id=-1, pad_id=-1)
```



In [5]:
sp = spm.SentencePieceProcessor(model_file='silero_tokens.model')

In [6]:
pieces = sp.encode_as_pieces("you are my best friend")
print(pieces)
pieces_with_spaces = [i.replace('▁', ' ') for i in pieces]
print(pieces_with_spaces)

['▁', 'you', '▁', 'are', '▁', 'my', '▁', 'best', '▁', 'friend']
[' ', 'you', ' ', 'are', ' ', 'my', ' ', 'best', ' ', 'friend']


# Silero

In [7]:
!pip install --quiet torch torchaudio soundfile omegaconf intel-tensorflow tensorflow_hub

     |████████████████████████████████| 1.9MB 7.9MB/s 
     |████████████████████████████████| 165.8MB 99kB/s 
     |████████████████████████████████| 645kB 57.4MB/s 


In [28]:
import os
import torch
import tensorflow as tf
import tensorflow_hub as tf_hub
from omegaconf import OmegaConf

language = 'en'

# load provided utils using torch.hub for brevity
_, decoder, utils = torch.hub.load('snakers4/silero-models', model='silero_stt', language=language)
(read_batch, split_into_batches, read_audio, prepare_model_input) = utils

# see available models
torch.hub.download_url_to_file('https://raw.githubusercontent.com/snakers4/silero-models/master/models.yml', 'models.yml')
models = OmegaConf.load('models.yml')
available_languages = list(models.stt_models.keys())
assert language in available_languages

# load the actual tf model
tf_model = tf_hub.load("https://storage.googleapis.com/ai-karaoke-311510-america/en_v2_tf.tar.gz")
#tf_model = tf_hub.load(models.stt_models.get(language).v2.tf)


Using cache found in /root/.cache/torch/hub/snakers4_silero-models_master


In [9]:
labels = models.stt_models.en.v2.labels
!wget $labels

--2021-04-25 10:10:17--  https://models.silero.ai/models/en/en_v1_labels.json
Resolving models.silero.ai (models.silero.ai)... 104.21.7.154, 172.67.130.83, 2606:4700:3034::6815:79a, ...
Connecting to models.silero.ai (models.silero.ai)|104.21.7.154|:443... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2021-04-25 10:10:17 ERROR 503: Service Temporarily Unavailable.



In [10]:
# download a single file, any format compatible with TorchAudio (soundfile backend)
torch.hub.download_url_to_file(models.stt_models.get(language).latest.meta.sample, dst = speech_file, progress=True)
test_files = [speech_file]
batches = split_into_batches(test_files, batch_size=10)
input = prepare_model_input(read_batch(batches[0]))

# tf inference
res = tf_model.signatures["serving_default"](tf.constant(input.numpy()))['output_0']
print(decoder(torch.Tensor(res.numpy())[0]))

NameError: ignored

In [ ]:
# construct a shape[1,136,999] tensor where the columns consist of a single 1 in one of the 136 and the others 0
# In this way I may find out what the 136 means

import numpy as np
value = 0
the_tensor = []
for i in range(136):
  if i == value:
    the_tensor.append(list(np.ones(999)))
  else:
    the_tensor.append(list(np.zeros(999)))

the_tensor = np.array(the_tensor)
the_tensor = the_tensor[np.newaxis, :]
#print(the_tensor.shape)
the_tensor = tf.convert_to_tensor(the_tensor)
print(the_tensor)


tf.Tensor(
[[[1. 1. 1. ... 1. 1. 1.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]], shape=(1, 136, 999), dtype=float64)


In [ ]:
#res = tf_model.signatures["serving_default"](tf.constant(input.numpy()))['output_0']
print(decoder(torch.Tensor(the_tensor.numpy())[0]))

# Test that the 999 does refer to time, and thus halving it will shorten the output
res = tf_model.signatures["serving_default"](tf.constant(input.numpy()))['output_0']
print(decoder(torch.Tensor(res.numpy())[0]))


the birch canoe slit on the smooth planks blared the sheet to the dark blue background it's easy to tell a depth of a well four hours of steady work faced us


In [ ]:
res1, res2 = tf.split(res, [500,499],2)
print(res1.shape)
#print(decoder(torch.Tensor(res1.numpy())[0]))
'''---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-38-617167afc803> in <module>()
      1 res1, res2 = tf.split(res, [500,499],2)
      2 print(res1.shape)
----> 3 print(decoder(torch.Tensor(res1.numpy())[0]))

1 frames
/root/.cache/torch/hub/snakers4_silero-models_master/utils.py in process(self, probs, wav_len, word_align)
     62     def process(self,
     63                 probs, wav_len, word_align):
---> 64         assert len(self.labels) == probs.shape[1]
     65         for_string = []
     66         argm = torch.argmax(probs, axis=1)

AssertionError: '''

(1, 136, 500)


'---------------------------------------------------------------------------\nAssertionError                            Traceback (most recent call last)\n<ipython-input-38-617167afc803> in <module>()\n      1 res1, res2 = tf.split(res, [500,499],2)\n      2 print(res1.shape)\n----> 3 print(decoder(torch.Tensor(res1.numpy())[0]))\n\n1 frames\n/root/.cache/torch/hub/snakers4_silero-models_master/utils.py in process(self, probs, wav_len, word_align)\n     62     def process(self,\n     63                 probs, wav_len, word_align):\n---> 64         assert len(self.labels) == probs.shape[1]\n     65         for_string = []\n     66         argm = torch.argmax(probs, axis=1)\n\nAssertionError: '

In [ ]:
# construct a shape[1,136,999] tensore where the columns consist of a single 1 in one of the 136 and the others 0
# In this way I may find out what the 136 means

import numpy as np
value = 11
the_tensor = []
for i in range(999):
  if i == value:
    temp = list(np.ones(136))
    temp[10] = 0
    the_tensor.append(temp)
  else:
    temp = list(np.zeros(136))
    the_tensor.append(temp)
    if i == 12:
      temp[10] = 1


the_tensor = np.array(the_tensor)
the_tensor = np.swapaxes(the_tensor, 0, 1)
the_tensor = the_tensor[np.newaxis, :]
#print(the_tensor.shape)
the_tensor = tf.convert_to_tensor(the_tensor)
print(the_tensor)

print(decoder(torch.Tensor(the_tensor.numpy())[0]))

tf.Tensor(
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]], shape=(1, 136, 999), dtype=float64)
entoen


In [ ]:
#@title Install dependencies

!pip install -q omegaconf
!pip install -q torchaudio
!pip install -q soundfile
!pip install -q pydub

import os
from os.path import exists

if not exists('silero-models'):
  !git clone -q --depth 1 https://github.com/snakers4/silero-models

%cd silero-models

# silero imports
import torch
import random
from glob import glob
from omegaconf import OmegaConf
from utils import (init_jit_model, 
                   split_into_batches,
                   read_audio,
                   read_batch,
                   prepare_model_input)
from colab_utils import (record_audio,
                         audio_bytes_to_np,
                         upload_audio)

device = torch.device('cpu')   # you can use any pytorch device
models = OmegaConf.load('models.yml')

# imports for uploading/recording
import numpy as np
import ipywidgets as widgets
from scipy.io import wavfile
from IPython.display import Audio, display, clear_output
from torchaudio.functional import vad


     |████████████████████████████████| 776.8MB 18kB/s 
ERROR: torchvision 0.8.1+cu101 has requirement torch==1.7.0, but you'll have torch 1.7.1 which is incompatible.
/content/silero-models


In [ ]:
sample_rate = 16000

clear_output()
audio = record_audio(10)
wavfile.write('/content/recorded.wav', sample_rate, (32767*audio).numpy().astype(np.int16))


#button = widgets.Button(description="Record Speech")
#button.on_click(_record_audio)
#display(button)

display(Audio(audio, rate=sample_rate, autoplay=True))
wavfile.write('test.wav', sample_rate, (32767*audio).numpy().astype(np.int16))
  

Starting recording for 10 seconds...


<IPython.core.display.Javascript object>

Finished recording!


In [ ]:
len(decoder.labels)

999

In [ ]:
decoder.blank_idx

0

In [25]:
#Testing singing
import numpy as np

speech_file = '/content/vocals.wav'
test_files = [speech_file]
batches = split_into_batches(test_files, batch_size=10)
input = prepare_model_input(read_batch(batches[0]))

# For each frame print the grapheme that is the most likely
graphemes = decoder.labels
res = tf_model.signatures["serving_default"](tf.constant(input.numpy()))['output_0']
res_array = np.array(res)
res_array[0].shape
result = np.argmax(res_array, axis=2)

text = []
for i in result[0].tolist():
  text.append(graphemes[i])

print("".join(text))
print(decoder(torch.Tensor(res.numpy())[0]))

____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________would_  not    _believe_       __eyes______  if  ten_  millillion  _f__ire_  _lili________ ___       the___  as i   fell__ _______________________________________because_  they   tellll  the  open____   _air_____  and _le_   your  dro_ps  every____where_   you      me_   will_  but_   i  would  just  _get_  them_________  ___________________________ _i_   like_    make_  my_____self______________________________________________________________________________________________________ _it_  hard_  to say_    i   ra_ther_____________________i____________________ _because_  _every_______   is   never______    _ _see______________________________________because  i   get_  

In [27]:
speech_file = '/content/vocals.wav'
test_files = [speech_file]
batches = split_into_batches(test_files, batch_size=10)
input = prepare_model_input(read_batch(batches[0]))
res = tf_model.signatures["serving_default"](tf.constant(input.numpy()))['output_0']
print(decoder(torch.Tensor(res.numpy())[0]))

would not believe eyes if ten million fire li the as i fell because they tellll the open air and le your drops everywhere you me will but i would just get them i like make myself it hard to say i ratheri because every is never seebecause i get a thousand hour from ten thousand lighting lawves they i teach me how ina str above i had saw companies my and go you to by thati i my is all see that i rather way ilyeverything is is we my just exactyou like such what you are hire of goting she not or you tored the all can million myyour eyes i h good li a gooddness the eyes as they say fa all where several are if my dreams get real bizar isay give you and i keep that in a yourari was my or i let ly is i eyes myseso all see i let long every is see i like make it are i because my first


In [69]:
np.argsort(res_array, axis=2)[0][100]
#result = np.argmax(res_array, axis=2)
#result[0][100]

array([685, 822, 617, 653, 750, 867, 765, 635, 811, 862, 590, 630, 818,
       743, 824, 769, 855, 956, 913, 660, 504, 493, 928, 600, 940, 597,
       857, 833, 821, 942, 298, 710, 618, 699, 914, 517, 424, 796, 903,
       485, 749, 948, 646, 306, 701, 797, 691, 385, 598, 768, 775, 720,
       889, 787, 915, 708, 530, 921, 712, 944, 838, 804, 794, 853, 683,
       947, 801, 876, 803, 318, 856, 548, 886, 835, 362, 631, 864, 714,
       946, 707, 799, 745, 870, 423, 264, 562, 941, 606, 850, 816, 958,
       782, 910, 960, 830, 880, 902, 413, 655, 620, 806, 593, 538, 753,
       497, 623, 945, 904, 579, 647, 754, 442, 380, 823, 795, 954, 908,
       916, 399, 462, 837, 934, 209, 875, 931, 836, 859, 694, 828, 924,
       456, 786, 243, 586, 353, 892, 395, 937, 664, 605, 711, 510, 505,
       687, 877, 431, 633, 878, 492, 681, 483, 778, 831, 737, 387, 777,
       447, 684, 780, 723, 402, 725, 364, 943, 693, 295, 852, 957, 772,
       808, 900, 495, 443, 891, 356, 848, 580, 905, 322, 658, 85

In [13]:
import math

subproblems = []
def minimal_token(text, tokens):
  global subproblems
  subproblems = [None for i in range(len(text))]
  # Solve all of the subproblems
  
  for i in range(len(text)):
    minimal_token_recursive(text, len(text) - 1 - i, tokens)
  solution = minimal_token_recursive(text, 0, tokens)
  return solution

def minimal_token_recursive(text, index, tokens):
  global subproblems
  if index >= len(text):
    return (0,[])
  # If we haven't calculated the solution before, calculate it now
  if subproblems[index] is None:
    subproblems[index] = minimal_token_recursive_calculate(text, index, tokens)
    
  return subproblems[index]
  


def minimal_token_recursive_calculate(text, index, tokens):
  minimum = None
  minimum_token = None
  for i, token in enumerate(tokens):
    if str.find(text[index:], token) == 0:
      subproblem = minimal_token_recursive(text, index+len(token), tokens)
      if subproblem is None:
        raise Exception("Sub none")
      if minimum is None or subproblem[0] < minimum[0]:
        minimum = subproblem
        minimum_token = i
  if minimum == None:
    #raise Exception("This text cannot be represented")
    # or instead just return something with a large cost
    return (math.inf, [])
  
  new_list = minimum[1].copy()
  new_list.insert(0, minimum_token)
  return (1 + minimum[0], new_list)

  


In [71]:
#minimal_token("the inovation sensation", decoder.labels)
minimal_token("the", decoder.labels)

(1, [2])

In [ ]:
decoder.

In [ ]:
str.find("hello", "ll")

In [ ]:
"hello"[0:]

In [ ]:
k = [1,2]
k.insert(2,0)
k

In [72]:
minimal_token("hello", ["he", "llo", "l", "lo", "o"])

(2, [0, 1])

In [73]:
minimal_token("hello", ["he", "llo", "l", "lo"])

(2, [0, 1])

In [ ]:
test = [1].append(k)
test

In [ ]:
res.shape

In [74]:
the_string = '''look at this stuff isnt it neat wouldn't you think my collection's complete wouldn't you think i'm the girl girl who has everything'''

minimal_token(the_string, decoder.labels)

(64,
 [221,
  998,
  8,
  998,
  75,
  998,
  25,
  980,
  621,
  998,
  10,
  974,
  970,
  998,
  17,
  998,
  74,
  8,
  998,
  184,
  974,
  991,
  970,
  998,
  37,
  998,
  258,
  998,
  113,
  998,
  432,
  24,
  413,
  991,
  975,
  998,
  836,
  87,
  998,
  184,
  974,
  991,
  970,
  998,
  37,
  998,
  258,
  998,
  973,
  991,
  982,
  998,
  2,
  998,
  968,
  998,
  968,
  998,
  171,
  998,
  230,
  998,
  294,
  131])

In [80]:
sp.encode_as_ids(the_string)

[999,
 222,
 999,
 9,
 999,
 76,
 999,
 26,
 981,
 622,
 999,
 11,
 975,
 971,
 999,
 18,
 999,
 75,
 9,
 999,
 185,
 975,
 992,
 971,
 999,
 38,
 999,
 259,
 999,
 114,
 999,
 433,
 25,
 414,
 992,
 976,
 999,
 837,
 88,
 999,
 185,
 975,
 992,
 971,
 999,
 38,
 999,
 259,
 999,
 974,
 992,
 983,
 999,
 3,
 999,
 969,
 999,
 969,
 999,
 172,
 999,
 231,
 999,
 295,
 132]

In [78]:
for i in range(len(labels)):
  if labels[i]

['_',
 'th',
 'the',
 'in',
 'an',
 're',
 'er',
 'on',
 'at',
 'ou',
 'is',
 'en',
 'to',
 'and',
 'ed',
 'al',
 'as',
 'it',
 'ing',
 'or',
 'of',
 'es',
 'ar',
 'he',
 'le',
 'st',
 'se',
 'om',
 'ic',
 'be',
 'we',
 'ly',
 'that',
 'no',
 'wh',
 've',
 'ha',
 'you',
 'ch',
 'ion',
 'il',
 'ent',
 'ro',
 'me',
 'id',
 'ac',
 'gh',
 'for',
 'was',
 'lo',
 'ver',
 'ut',
 'li',
 'ld',
 'ay',
 'ad',
 'so',
 'ir',
 'im',
 'un',
 'wi',
 'ter',
 'are',
 'with',
 'ke',
 'ge',
 'do',
 'ur',
 'all',
 'ce',
 'ab',
 'mo',
 'go',
 'pe',
 'ne',
 'this',
 'ri',
 'ght',
 'de',
 'one',
 'us',
 'am',
 'out',
 'fe',
 'but',
 'po',
 'his',
 'te',
 'ho',
 'ther',
 'not',
 'con',
 'com',
 'll',
 'they',
 'if',
 'ould',
 'su',
 'have',
 'ct',
 'ain',
 'our',
 'ation',
 'fr',
 'ill',
 'now',
 'sa',
 'had',
 'tr',
 'her',
 'per',
 'ant',
 'oun',
 'my',
 'ul',
 'ca',
 'by',
 'what',
 'red',
 'res',
 'od',
 'ome',
 'ess',
 'man',
 'ex',
 'she',
 'pl',
 'co',
 'wor',
 'pro',
 'up',
 'thing',
 'there',
 'ple',


In [77]:
decoder.labels

['_',
 'th',
 'the',
 'in',
 'an',
 're',
 'er',
 'on',
 'at',
 'ou',
 'is',
 'en',
 'to',
 'and',
 'ed',
 'al',
 'as',
 'it',
 'ing',
 'or',
 'of',
 'es',
 'ar',
 'he',
 'le',
 'st',
 'se',
 'om',
 'ic',
 'be',
 'we',
 'ly',
 'that',
 'no',
 'wh',
 've',
 'ha',
 'you',
 'ch',
 'ion',
 'il',
 'ent',
 'ro',
 'me',
 'id',
 'ac',
 'gh',
 'for',
 'was',
 'lo',
 'ver',
 'ut',
 'li',
 'ld',
 'ay',
 'ad',
 'so',
 'ir',
 'im',
 'un',
 'wi',
 'ter',
 'are',
 'with',
 'ke',
 'ge',
 'do',
 'ur',
 'all',
 'ce',
 'ab',
 'mo',
 'go',
 'pe',
 'ne',
 'this',
 'ri',
 'ght',
 'de',
 'one',
 'us',
 'am',
 'out',
 'fe',
 'but',
 'po',
 'his',
 'te',
 'ho',
 'ther',
 'not',
 'con',
 'com',
 'll',
 'they',
 'if',
 'ould',
 'su',
 'have',
 'ct',
 'ain',
 'our',
 'ation',
 'fr',
 'ill',
 'now',
 'sa',
 'had',
 'tr',
 'her',
 'per',
 'ant',
 'oun',
 'my',
 'ul',
 'ca',
 'by',
 'what',
 'red',
 'res',
 'od',
 'ome',
 'ess',
 'man',
 'ex',
 'she',
 'pl',
 'co',
 'wor',
 'pro',
 'up',
 'thing',
 'there',
 'ple',


In [12]:
import math


subproblems = []
space_index = decoder.labels.index(' ')
def forced_alignment(correct_text, text_from_speech):
  global subproblems
  subproblems = []

  time_values = np.array(text_from_speech).shape[0]

  for i in range(len(correct_text)):
    subproblems.append([])
    for j in range(time_values):
      subproblems[-1].append(None)

  for i in range(len(correct_text)):
    for j in range(time_values):
      forced_alignment_recursive(correct_text, text_from_speech, i, j)

  
  #solution = forced_alignment_recursive(correct_text, text_from_speech, len(correct_text) - 1, time_values - 1)

  solution = []
  value = len(correct_text) - 1
  for i in range(time_values):
    
    solution.append(value)
    time = time_values - 1 - i
    value -= subproblems[value][time][1]
    


  solution.reverse()

  return solution

def forced_alignment_recursive(correct_text, text_from_speech, text_index, time):
  global subproblems
  
  
  if time < text_index or text_index < 0:
    return (-math.inf, 0)
  
  

  # If we haven't calculated the solution before, calculate it now
  try:
    subproblems[text_index][time]
  except:
    print(text_index, time)

  if subproblems[text_index][time] is None:
    subproblems[text_index][time] = forced_alignment_recursive_calculate(correct_text, text_from_speech, text_index, time)
    
  return subproblems[text_index][time]
  


def forced_alignment_recursive_calculate(correct_text, text_from_speech, text_index, time):
  if time == 0:
    return (0, 0)
  text = correct_text[text_index]
  # Replace spaces with the unknown symbol
  global space_index
  if text == space_index:
    text = 0

  probability = math.log(text_from_speech[time][text])

  


  

  
  options = [forced_alignment_recursive(correct_text, text_from_speech, text_index, time - 1),
             forced_alignment_recursive(correct_text, text_from_speech, text_index - 1, time - 1),
  ]

  option_probabilities = [i[0] for i in options]
  options_index = np.argmax(option_probabilities)

  #indexes = options[options_index][1].copy()
  #indexes.append(text_index)
  return (options[options_index][0] + probability, options_index)







  '''minimum = None
  minimum_token = None
  for i, token in enumerate(tokens):
    if str.find(text[index:], token) == 0:
      subproblem = forced_alignment_recursive(text, index+len(token), tokens)
      if subproblem is None:
        raise Exception("Sub none")
      if minimum is None or subproblem[0] < minimum[0]:
        minimum = subproblem
        minimum_token = i
  if minimum == None:
    #raise Exception("This text cannot be represented")
    # or instead just return something with a large cost
    return (math.inf, [])
  
  new_list = minimum[1].copy()
  new_list.insert(0, minimum_token)
  return (1 + minimum[0], new_list)'''

  


In [ ]:
test = [1,3]
np.argmax(test)

In [ ]:
math.log(5)

In [115]:
import string
#text = '''you would not believe your eyes if ten million fireflies lit up the world as i fell asleep cause they fill the open air and leave teardrops everywhere you'd think me rude but i would just stand and stare i'd like to make myself believe that planet earth turns slowly it's hard to say that i'd rather stay awake when i'm asleep cause everything is never as it seems cause i'd get a thousand hugs from ten thousand lightning bugs as they tried to teach me how to dance a foxtrot above my head'''

text_lines_original = '''You would not believe your eyes
If ten million fireflies
Lit up the world as I fell asleep
'Cause they fill the open air
And leave teardrops everywhere
You'd think me rude but I would just stand and stare
I'd like to make myself believe that planet earth turns slowly
It's hard to say that I'd rather stay awake when I'm asleep
'Cause everything is never as it seems
'Cause I'd get a thousand hugs
From ten thousand lightning bugs
As they tried to teach me how to dance
A foxtrot above my head
A sock-hop beneath my bed
A disco ball is just hanging by a thread (thread, thread)
I'd like to make myself believe that planet earth turns slowly
It's hard to say that I'd rather stay awake when I'm asleep
'Cause everything is never as it seems (when I fall asleep)
Leave my door open just a crack
Please take me away from here
'Cause I feel like such an insomniac
Please take me away from here
Why do I tire of counting sheep?
Please take me away from here
When I'm far too tired to fall asleep
To ten million fireflies
I'm weird 'cause I hate goodbyes
I got misty eyes as they said farewell (they said farewell)
But I'll know where several are
If my dreams get real bizarre
'Cause I saved a few and I keep them in a jar (jar, jar, jar)
I'd like to make myself believe that planet earth turns slowly
It's hard to say that I'd rather stay awake when I'm asleep
'Cause everything is never as it seems (when I fall asleep)
I'd like to make myself believe that planet earth turns slowly
It's hard to say that I'd rather stay awake when I'm asleep
'Cause everything is never as it seems (when I fall asleep)'''

text_lines_original_list = text_lines_original.split('\n')

'''text = Namida nagasu koto sura nai mama
Sugoshita hibi no ato hitotsu mo nokosazu ni
Sayonara da

Hitori de mukaeta asa ni
Narihibiku dareka no oto
Futari de sugoshita heya de
Me wo tojita mama kangaeteta

Warui no wa dare da
Wakannai yo
Dare no sei demo nai
Tabun

Bokura wa nankai datte kitto
Sou nannen datte kitto
Sayonara to tomo ni owaru dake nan da
Shikata ga nai yo kitto
“Okaeri”
Omowazu koboreta kotoba wa
Chigau na

Hitori de mukaeta asa ni
Futo omou dareka no koto
Futari de sugoshita hibi no
Atarimae ga mada nokotteiru
Warui no wa kimi da
Sou dakke
Warui no wa boku da
Tabun

Kore mo taishuuteki renai desho
Sore wa saishuuteki na kotae da yo
Bokura dandan to zurete itta no
Sore mo tada yoku arukiki nareta sutoorii da
Anna ni kagayaiteita hibi ni sura
Hokori wa tsumotte ikun da

Bokura wa nankai datte kitto
Sou nannen datte kitto
Sayonara ni tsuzuku michi wo arukun da
Shikata ga nai yo kitto
“Okaeri”
Itsumo no you ni
Koboreochita

Wakariaenai koto nante sa
Ikura demo arun da kitto
Subete wo yurushiaeru wake janai kara
Tada, yasashisa no hibi wo
Tsurai hibi to kanjite shimatta no nara
Modorenai kara
Bokura wa nankai datte kitto
Bokura wa nankai datte kitto
Sou nannen datte kitto
Sayonara to tomo ni owaru dake nan da
Shikata ga nai yo kitto
“Okaeri”
Omowazu koboreta kotoba wa
Chigau na

Sore demo nankai datte kitto
Sou nannen datte kitto
Hajimari ni modoru koto ga dekita nara
Nante, omotte shimau yo
“Okaeri”
Todokazu koboreta kotoba ni
Waratta
Sukoshi hieta asa da'''

def parse_lyrics(text):
  letters = string.ascii_lowercase + ' ' + '\''
  new = text.lower()
  new = new.replace('\n', ' ')
  new = "".join([i for i in new if i in letters])
  # put a space at the start and at the end
  new = ' ' + new + ' '
  return new

def parse_lines(lines):
  lines = lines.split('\n')
  new_lines = []
  for line in lines:
    new_lines.append(parse_lyrics(line))
  return new_lines

text = parse_lyrics(text_lines_original)
print(text)
text_lines = parse_lines(text_lines_original)

 you would not believe your eyes if ten million fireflies lit up the world as i fell asleep 'cause they fill the open air and leave teardrops everywhere you'd think me rude but i would just stand and stare i'd like to make myself believe that planet earth turns slowly it's hard to say that i'd rather stay awake when i'm asleep 'cause everything is never as it seems 'cause i'd get a thousand hugs from ten thousand lightning bugs as they tried to teach me how to dance a foxtrot above my head a sockhop beneath my bed a disco ball is just hanging by a thread thread thread i'd like to make myself believe that planet earth turns slowly it's hard to say that i'd rather stay awake when i'm asleep 'cause everything is never as it seems when i fall asleep leave my door open just a crack please take me away from here 'cause i feel like such an insomniac please take me away from here why do i tire of counting sheep please take me away from here when i'm far too tired to fall asleep to ten million 

In [92]:
correct_text = minimal_token(text, decoder.labels)[1]

In [93]:
text

" you would not believe your eyes if ten million fireflies lit up the world as i fell asleep 'cause they fill the open air and leave teardrops everywhere you'd think me rude but i would just stand and stare i'd like to make myself believe that planet earth turns slowly it's hard to say that i'd rather stay awake when i'm asleep 'cause everything is never as it seems 'cause i'd get a thousand hugs from ten thousand lightning bugs as they tried to teach me how to dance a foxtrot above my head a sockhop beneath my bed a disco ball is just hanging by a thread thread thread i'd like to make myself believe that planet earth turns slowly it's hard to say that i'd rather stay awake when i'm asleep 'cause everything is never as it seems when i fall asleep leave my door open just a crack please take me away from here 'cause i feel like such an insomniac please take me away from here why do i tire of counting sheep please take me away from here when i'm far too tired to fall asleep to ten million

In [96]:
import numpy as np
correct_text = minimal_token(text, decoder.labels)[1]

#speech_file = '/content/fireflies_voc_1min.wav'
speech_file = '/content/vocals.wav'
#speech_file = '/content/tabun_voc.wav'
test_files = [speech_file]
batches = split_into_batches(test_files, batch_size=10)
input = prepare_model_input(read_batch(batches[0]))

graphemes = decoder.labels
res = tf_model.signatures["serving_default"](tf.constant(input.numpy()))['output_0']
text_from_speech = np.array(res)[0]

In [97]:
result_tokens = forced_alignment(correct_text, text_from_speech)
result = [decoder.labels[correct_text[i]] for i in result_tokens]
print(result)

[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',

# Make the subtitles

In [ ]:
!pip install srt

  Created wheel for srt: filename=srt-3.4.1-cp36-none-any.whl size=20571 sha256=32facf7f3c1979966a5c8a8ee2c11058f2a61a6d7d91f1e8a4746767be077a02
  Stored in directory: /root/.cache/pip/wheels/85/9e/29/17bfa5b6d3ce3c026b6bdf49557a269e0ef869492a1bc700b2
Successfully built srt


In [99]:
subtitles = result

original_text = text
original_text = [i for i in original_text.split(" ") if i is not '']




```python
current_word = 0
current_time = 0

time_stamps = []
in_a_word = False
for time, symbol in enumerate(subtitles):
  if symbol is not ' ' and not in_a_word:
    time_stamps.append((time, original_text[current_word]))
    in_a_word = True
    current_word += 1
  if symbol is ' ' and in_a_word:
    in_a_word = False

time_stamps.append((len(subtitles) - 1, 'FINSIH'))
```



In [55]:
string = text_lines[0]

In [58]:
string.find('test')

-1

In [118]:
current_word = -1
current_time = 0

line_index = -1
line = ''
previous = ' '

line_times = []
 
time_stamps = []
in_a_word = False
for time, symbol in enumerate(subtitles):
  
    
  if symbol is not ' ' and not in_a_word:
    
    if line.replace(' ', '') == '':
      line_index += 1
      # remove leading space from line
      line = text_lines[line_index][1:]
      line_times.append((int(time)*int(1000/12.5), text_lines_original_list[line_index]))
      
    line = line[line.find(' ')+1:]



    #time_stamps.append((time, original_text[current_word]))
    in_a_word = True
    current_word += 1
    #print(time, current_word, line)
  if symbol is ' ' and in_a_word:
    in_a_word = False
 
time_stamps.append((len(subtitles) - 1, 'FINSIH'))

In [119]:
print(line_times)

[(25920, 'You would not believe your eyes'), (28320, 'If ten million fireflies'), (31200, 'Lit up the world as I fell asleep'), (36160, "'Cause they fill the open air"), (38800, 'And leave teardrops everywhere'), (40800, "You'd think me rude but I would just stand and stare"), (47040, "I'd like to make myself believe that planet earth turns slowly"), (57120, "It's hard to say that I'd rather stay awake when I'm asleep"), (62400, "'Cause everything is never as it seems"), (68240, "'Cause I'd get a thousand hugs"), (70960, 'From ten thousand lightning bugs'), (73520, 'As they tried to teach me how to dance'), (79040, 'A foxtrot above my head'), (81680, 'A sock-hop beneath my bed'), (83920, 'A disco ball is just hanging by a thread (thread, thread)'), (89680, "I'd like to make myself believe that planet earth turns slowly"), (99760, "It's hard to say that I'd rather stay awake when I'm asleep"), (105280, "'Cause everything is never as it seems (when I fall asleep)"), (113680, 'Leave my do

In [123]:
prev = 0
texts = []
times = []
for index in range(len(line_times)):
  if index == 0:
    text = ''
  else:
    text = line_times[index - 1][1]
  time = line_times[index][0]
  times.append(time - prev)
  texts.append(text)
  prev = time



In [124]:
texts

['',
 'You would not believe your eyes',
 'If ten million fireflies',
 'Lit up the world as I fell asleep',
 "'Cause they fill the open air",
 'And leave teardrops everywhere',
 "You'd think me rude but I would just stand and stare",
 "I'd like to make myself believe that planet earth turns slowly",
 "It's hard to say that I'd rather stay awake when I'm asleep",
 "'Cause everything is never as it seems",
 "'Cause I'd get a thousand hugs",
 'From ten thousand lightning bugs',
 'As they tried to teach me how to dance',
 'A foxtrot above my head',
 'A sock-hop beneath my bed',
 'A disco ball is just hanging by a thread (thread, thread)',
 "I'd like to make myself believe that planet earth turns slowly",
 "It's hard to say that I'd rather stay awake when I'm asleep",
 "'Cause everything is never as it seems (when I fall asleep)",
 'Leave my door open just a crack',
 'Please take me away from here',
 "'Cause I feel like such an insomniac",
 'Please take me away from here',
 'Why do I tire o

In [125]:
times

[25920,
 2400,
 2880,
 4960,
 2640,
 2000,
 6240,
 10080,
 5280,
 5840,
 2720,
 2560,
 5520,
 2640,
 2240,
 5760,
 10080,
 5520,
 8400,
 2480,
 2640,
 3280,
 2880,
 2400,
 2080,
 5520,
 2560,
 2640,
 5360,
 2640,
 2160,
 6080,
 9920,
 5600,
 5840,
 10000,
 5520]

In [ ]:
import srt
from srt import Subtitle
import datetime


subs = []

for i, _ in enumerate(time_stamps):
  if i == len(time_stamps) - 1:
    break
  time_start = time_stamps[i][0] / 12.5
  time_end = time_stamps[i+1][0] / 12.5
  subs.append(Subtitle(index=i+1, start=datetime.timedelta(0, time_start, 0), end=datetime.timedelta(0, time_end, 0), content=time_stamps[i][1], proprietary=''))

print(srt.compose(subs))


1
00:00:03,520 --> 00:00:05,520
namida

2
00:00:05,520 --> 00:00:06,320
nagasu

3
00:00:06,320 --> 00:00:06,640
koto

4
00:00:06,640 --> 00:00:06,880
sura

5
00:00:06,880 --> 00:00:07,120
nai

6
00:00:07,120 --> 00:00:07,360
mama

7
00:00:07,360 --> 00:00:07,840
sugoshita

8
00:00:07,840 --> 00:00:08,160
hibi

9
00:00:08,160 --> 00:00:08,320
no

10
00:00:08,320 --> 00:00:08,560
ato

11
00:00:08,560 --> 00:00:08,960
hitotsu

12
00:00:08,960 --> 00:00:09,120
mo

13
00:00:09,120 --> 00:00:09,680
nokosazu

14
00:00:09,680 --> 00:00:10,240
ni

15
00:00:10,240 --> 00:00:10,640
sayonara

16
00:00:10,640 --> 00:00:10,960
da

17
00:00:10,960 --> 00:00:11,520
hitori

18
00:00:11,520 --> 00:00:12,240
demukaetaasa

19
00:00:12,240 --> 00:00:12,480
ni

20
00:00:12,480 --> 00:00:13,120
narihibiku

21
00:00:13,120 --> 00:00:13,760
darekano

22
00:00:13,760 --> 00:00:14,000
oto

23
00:00:14,000 --> 00:00:14,320
futari

24
00:00:14,320 --> 00:00:14,480
de

25
00:00:14,480 --> 00:00:14,960
sugoshita

26

In [ ]:
time_stamps

[(44, 'namida'),
 (69, 'nagasu'),
 (79, 'koto'),
 (83, 'sura'),
 (86, 'nai'),
 (89, 'mama'),
 (92, 'sugoshita'),
 (98, 'hibi'),
 (102, 'no'),
 (104, 'ato'),
 (107, 'hitotsu'),
 (112, 'mo'),
 (114, 'nokosazu'),
 (121, 'ni'),
 (128, 'sayonara'),
 (133, 'da'),
 (137, 'hitori'),
 (144, 'demukaetaasa'),
 (153, 'ni'),
 (156, 'narihibiku'),
 (164, 'darekano'),
 (172, 'oto'),
 (175, 'futari'),
 (179, 'de'),
 (181, 'sugoshita'),
 (187, 'heya'),
 (191, 'de'),
 (193, 'mewo'),
 (196, 'tojita'),
 (201, 'mama'),
 (204, 'kangaeteta'),
 (212, 'warui'),
 (264, 'no'),
 (268, 'wa'),
 (270, 'dare'),
 (273, 'da'),
 (276, 'wakannai'),
 (282, 'yo'),
 (285, 'dare'),
 (355, 'noseidemonai'),
 (362, 'tabun'),
 (367, 'bokura'),
 (372, 'wa'),
 (374, 'nankaidatte'),
 (384, 'kitto'),
 (388, 'sou'),
 (390, 'nannendatte'),
 (397, 'kitto'),
 (401, 'sayonara'),
 (406, 'to'),
 (408, 'tomo'),
 (413, 'ni'),
 (417, 'owaru'),
 (421, 'dake'),
 (426, 'nan'),
 (429, 'da'),
 (432, 'shikata'),
 (438, 'ga'),
 (440, 'nai'),
 (443, 

In [ ]:
subtitles

# Python Code

In [129]:
!pip install --quiet torch omegaconf intel-tensorflow tensorflow_hub

In [130]:
!wget https://storage.googleapis.com/ai-karaoke-311510-america/silero_tokens.model
!wget https://storage.googleapis.com/ai-karaoke-311510-america/vocals.wa

language = 'en'

# load provided utils using torch.hub for brevity
_, decoder, utils = torch.hub.load('snakers4/silero-models', model='silero_stt', language=language)
(read_batch, split_into_batches, read_audio, prepare_model_input) = utils

# see available models
torch.hub.download_url_to_file('https://raw.githubusercontent.com/snakers4/silero-models/master/models.yml', 'models.yml')
models = OmegaConf.load('models.yml')
available_languages = list(models.stt_models.keys())
assert language in available_languages

# load the actual tf model
tf_model = tf_hub.load("https://storage.googleapis.com/ai-karaoke-311510-america/en_v2_tf.tar.gz")

--2021-04-25 13:31:26--  https://storage.googleapis.com/ai-karaoke-311510-america/silero_tokens.model
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.142.128, 74.125.195.128, 74.125.20.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.142.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 258689 (253K) [application/octet-stream]
Saving to: ‘silero_tokens.model.2’

silero_tokens.model 100%[===================>] 252.63K  --.-KB/s    in 0.002s  

2021-04-25 13:31:26 (119 MB/s) - ‘silero_tokens.model.2’ saved [258689/258689]

--2021-04-25 13:31:26--  https://storage.googleapis.com/ai-karaoke-311510-america/vocals.wa
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.142.128, 74.125.195.128, 173.194.202.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.142.128|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-04-25 13:31:26 ERROR 404: Not Found.

Using cache found in /root/.cache/torch/hub/snakers4_silero-models_master


In [131]:
text_lines_original = '''You would not believe your eyes
If ten million fireflies
Lit up the world as I fell asleep
'Cause they fill the open air
And leave teardrops everywhere
You'd think me rude but I would just stand and stare
I'd like to make myself believe that planet earth turns slowly
It's hard to say that I'd rather stay awake when I'm asleep
'Cause everything is never as it seems
'Cause I'd get a thousand hugs
From ten thousand lightning bugs
As they tried to teach me how to dance
A foxtrot above my head
A sock-hop beneath my bed
A disco ball is just hanging by a thread (thread, thread)
I'd like to make myself believe that planet earth turns slowly
It's hard to say that I'd rather stay awake when I'm asleep
'Cause everything is never as it seems (when I fall asleep)
Leave my door open just a crack
Please take me away from here
'Cause I feel like such an insomniac
Please take me away from here
Why do I tire of counting sheep?
Please take me away from here
When I'm far too tired to fall asleep
To ten million fireflies
I'm weird 'cause I hate goodbyes
I got misty eyes as they said farewell (they said farewell)
But I'll know where several are
If my dreams get real bizarre
'Cause I saved a few and I keep them in a jar (jar, jar, jar)
I'd like to make myself believe that planet earth turns slowly
It's hard to say that I'd rather stay awake when I'm asleep
'Cause everything is never as it seems (when I fall asleep)
I'd like to make myself believe that planet earth turns slowly
It's hard to say that I'd rather stay awake when I'm asleep
'Cause everything is never as it seems (when I fall asleep)'''

import os
import torch
import tensorflow as tf
import tensorflow_hub as tf_hub
from omegaconf import OmegaConf
import numpy as np
import math
import string

subproblems = []
def minimal_token(text, tokens):
  global subproblems
  subproblems = [None for i in range(len(text))]
  # Solve all of the subproblems
  
  for i in range(len(text)):
    minimal_token_recursive(text, len(text) - 1 - i, tokens)
  solution = minimal_token_recursive(text, 0, tokens)
  return solution

def minimal_token_recursive(text, index, tokens):
  global subproblems
  if index >= len(text):
    return (0,[])
  # If we haven't calculated the solution before, calculate it now
  if subproblems[index] is None:
    subproblems[index] = minimal_token_recursive_calculate(text, index, tokens)
    
  return subproblems[index]
  
def minimal_token_recursive_calculate(text, index, tokens):
  minimum = None
  minimum_token = None
  for i, token in enumerate(tokens):
    if str.find(text[index:], token) == 0:
      subproblem = minimal_token_recursive(text, index+len(token), tokens)
      if subproblem is None:
        raise Exception("Sub none")
      if minimum is None or subproblem[0] < minimum[0]:
        minimum = subproblem
        minimum_token = i
  if minimum == None:
    #raise Exception("This text cannot be represented")
    # or instead just return something with a large cost
    return (math.inf, [])
  
  new_list = minimum[1].copy()
  new_list.insert(0, minimum_token)
  return (1 + minimum[0], new_list)

subproblems = []
space_index = decoder.labels.index(' ')
def forced_alignment(correct_text, text_from_speech):
  global subproblems
  subproblems = []

  time_values = np.array(text_from_speech).shape[0]

  for i in range(len(correct_text)):
    subproblems.append([])
    for j in range(time_values):
      subproblems[-1].append(None)

  for i in range(len(correct_text)):
    for j in range(time_values):
      forced_alignment_recursive(correct_text, text_from_speech, i, j)

  solution = []
  value = len(correct_text) - 1
  for i in range(time_values):
    
    solution.append(value)
    time = time_values - 1 - i
    value -= subproblems[value][time][1]
    
  solution.reverse()
  return solution

def forced_alignment_recursive(correct_text, text_from_speech, text_index, time):
  global subproblems
  
  if time < text_index or text_index < 0:
    return (-math.inf, 0)
  
  # If we haven't calculated the solution before, calculate it now
  try:
    subproblems[text_index][time]
  except:
    print(text_index, time)

  if subproblems[text_index][time] is None:
    subproblems[text_index][time] = forced_alignment_recursive_calculate(correct_text, text_from_speech, text_index, time)
    
  return subproblems[text_index][time]
  
def forced_alignment_recursive_calculate(correct_text, text_from_speech, text_index, time):
  if time == 0:
    return (0, 0)
  text = correct_text[text_index]
  # Replace spaces with the unknown symbol
  global space_index
  if text == space_index:
    text = 0

  probability = math.log(text_from_speech[time][text])

  options = [forced_alignment_recursive(correct_text, text_from_speech, text_index, time - 1),
             forced_alignment_recursive(correct_text, text_from_speech, text_index - 1, time - 1),
  ]

  option_probabilities = [i[0] for i in options]
  options_index = np.argmax(option_probabilities)

  return (options[options_index][0] + probability, options_index)

text_lines_original_list = text_lines_original.split('\n')


def parse_lyrics(text):
  letters = string.ascii_lowercase + ' ' + '\''
  new = text.lower()
  new = new.replace('\n', ' ')
  new = "".join([i for i in new if i in letters])
  # put a space at the start and at the end
  new = ' ' + new + ' '
  return new

def parse_lines(lines):
  lines = lines.split('\n')
  new_lines = []
  for line in lines:
    new_lines.append(parse_lyrics(line))
  return new_lines

text = parse_lyrics(text_lines_original)
text_lines = parse_lines(text_lines_original)

correct_text = minimal_token(text, decoder.labels)[1]

speech_file = '/content/vocals.wav'
test_files = [speech_file]
batches = split_into_batches(test_files, batch_size=10)
input = prepare_model_input(read_batch(batches[0]))

res = tf_model.signatures["serving_default"](tf.constant(input.numpy()))['output_0']
text_from_speech = np.array(res)[0]
result_tokens = forced_alignment(correct_text, text_from_speech)
result = [decoder.labels[correct_text[i]] for i in result_tokens]

current_word = -1
line_index = -1
line = ''
line_times = []
in_a_word = False
for time, symbol in enumerate(result):

  if symbol is not ' ' and not in_a_word:
    
    if line.replace(' ', '') == '':
      line_index += 1
      # remove leading space from line
      line = text_lines[line_index][1:]
      line_times.append((int(time)*int(1000/12.5), text_lines_original_list[line_index]))
    line = line[line.find(' ')+1:]
    in_a_word = True
    current_word += 1
  if symbol is ' ' and in_a_word:
    in_a_word = False

prev = 0
texts = []
times = []
for index in range(len(line_times)):
  if index == 0:
    text = ''
  else:
    text = line_times[index - 1][1]
  time = line_times[index][0]
  times.append(time - prev)
  texts.append(text)
  prev = time

 you would not believe your eyes if ten million fireflies lit up the world as i fell asleep 'cause they fill the open air and leave teardrops everywhere you'd think me rude but i would just stand and stare i'd like to make myself believe that planet earth turns slowly it's hard to say that i'd rather stay awake when i'm asleep 'cause everything is never as it seems 'cause i'd get a thousand hugs from ten thousand lightning bugs as they tried to teach me how to dance a foxtrot above my head a sockhop beneath my bed a disco ball is just hanging by a thread thread thread i'd like to make myself believe that planet earth turns slowly it's hard to say that i'd rather stay awake when i'm asleep 'cause everything is never as it seems when i fall asleep leave my door open just a crack please take me away from here 'cause i feel like such an insomniac please take me away from here why do i tire of counting sheep please take me away from here when i'm far too tired to fall asleep to ten million 

In [127]:
texts

['',
 'You would not believe your eyes',
 'If ten million fireflies',
 'Lit up the world as I fell asleep',
 "'Cause they fill the open air",
 'And leave teardrops everywhere',
 "You'd think me rude but I would just stand and stare",
 "I'd like to make myself believe that planet earth turns slowly",
 "It's hard to say that I'd rather stay awake when I'm asleep",
 "'Cause everything is never as it seems",
 "'Cause I'd get a thousand hugs",
 'From ten thousand lightning bugs',
 'As they tried to teach me how to dance',
 'A foxtrot above my head',
 'A sock-hop beneath my bed',
 'A disco ball is just hanging by a thread (thread, thread)',
 "I'd like to make myself believe that planet earth turns slowly",
 "It's hard to say that I'd rather stay awake when I'm asleep",
 "'Cause everything is never as it seems (when I fall asleep)",
 'Leave my door open just a crack',
 'Please take me away from here',
 "'Cause I feel like such an insomniac",
 'Please take me away from here',
 'Why do I tire o

In [128]:
times

[25920,
 2400,
 2880,
 4960,
 2640,
 2000,
 6240,
 10080,
 5280,
 5840,
 2720,
 2560,
 5520,
 2640,
 2240,
 5760,
 10080,
 5520,
 8400,
 2480,
 2640,
 3280,
 2880,
 2400,
 2080,
 5520,
 2560,
 2640,
 5360,
 2640,
 2160,
 6080,
 9920,
 5600,
 5840,
 10000,
 5520]